[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid

[program:xvfb]
command=Xvfb %(ENV_DISPLAY)s -screen 0 %(ENV_SCREEN_WIDTH)sx%(ENV_SCREEN_HEIGHT)sx%(ENV_SCREEN_DEPTH)s -ac +extension GLX +render -noreset
autorestart=true
priority=10
startsecs=2

[program:metacity]
command=/usr/local/bin/wait-for-display.sh metacity --display=%(ENV_DISPLAY)s --replace
environment=DISPLAY="%(ENV_DISPLAY)s"
autorestart=true
priority=20
startsecs=2

[program:x11vnc]
command=x11vnc -display %(ENV_DISPLAY)s -forever -shared -nopw -rfbport %(ENV_VNC_PORT)s -xkb
autorestart=true
priority=30

[program:novnc]
command=websockify --web /usr/share/novnc %(ENV_NOVNC_PORT)s localhost:%(ENV_VNC_PORT)s
autorestart=true
priority=40
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
